# **Learn, Love, Live**

In [53]:
print("jai maa kali")

jai maa kali

In [54]:
# understand or working with dataframe modules
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")


# model building modules
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


# Display settings for pandas DataFrames
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_rows', None)     # Show all rows
pd.set_option('display.max_colwidth', None) # Show full column content
pd.set_option('display.width', None)        # Auto-detect terminal width
pd.set_option('display.expand_frame_repr', False) # Don't wrap to multiple pages

## **Start**

In [ ]:
gym = pd.read_csv("data/model_data/volumne_reps_sets.csv")
`gym

   user_id  exercise_id muscle_group body_part   phase difficulty_level    equipment session_date day_type  sets_planned  reps_planned  weight_planned  sets_completed  reps_completed  weight_used  rpe  rest_time_sec  completion_rate  next_sets  next_reps  next_weight
0      101            1  hip_flexors     waist    main         Beginner  body_weight   2025-01-01      abs             3            15               0               3              15            0    6             60             1.00          3         18            0
1      101            1  hip_flexors     waist    main         Beginner  body_weight   2025-01-04      abs             3            18               0               3              18            0    5             60             1.00          4         20            0
2      102           45   quadriceps      legs    main     Intermediate      barbell   2025-01-02     legs             4             8              80               4               7           80    8            120             0.87          4          8           85
3      102           45   quadriceps      legs    main     Intermediate      barbell   2025-01-06     legs             4             8              85               4               8           85    7            120             1.00          5          6           90
4      103           78   hamstrings      legs  warmup         Beginner  body_weight   2025-01-03     legs             2            12               0               2              12            0    4             45             1.00          2         15            0
5      104           90    full_body     relax   relax         Beginner         none   2025-01-03     legs             1            10               0               1              10            0    2             30             1.00          1         10            0

## **EDA**

In [56]:
gym.shape

(6, 21)

In [57]:
gym.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           6 non-null      int64
 1   exercise_id       6 non-null      int64
 2   muscle_group      6 non-null      object
 3   body_part         6 non-null      object
 4   phase             6 non-null      object
 5   difficulty_level  6 non-null      object
 6   equipment         6 non-null      object
 7   session_date      6 non-null      object
 8   day_type          6 non-null      object
 9   sets_planned      6 non-null      int64
 10  reps_planned      6 non-null      int64
 11  weight_planned    6 non-null      int64
 12  sets_completed    6 non-null      int64
 13  reps_completed    6 non-null      int64
 14  weight_used       6 non-null      int64
 15  rpe               6 non-null      int64
 16  rest_time_sec     6 non-null      int64
 17  completion_rate   6 non-null      float64
 18  next_sets         6 non-null      int64
 19  next_reps         6 non-null      int64
 20  next_weight       6 non-null      int64
dtypes: float64(1), int64(13), object(7)
memory usage: 1.1+ KB

In [58]:
unwanted_cols = ['user_id', 'session_date']
clean_Df = gym.drop(columns=unwanted_cols)

In [59]:
for col in clean_Df.columns:
    print(f'    "{col}:"",')

    "exercise_id:"",
    "muscle_group:"",
    "body_part:"",
    "phase:"",
    "difficulty_level:"",
    "equipment:"",
    "day_type:"",
    "sets_planned:"",
    "reps_planned:"",
    "weight_planned:"",
    "sets_completed:"",
    "reps_completed:"",
    "weight_used:"",
    "rpe:"",
    "rest_time_sec:"",
    "completion_rate:"",
    "next_sets:"",
    "next_reps:"",
    "next_weight:"",

## **Model**

In [60]:
model_Df = clean_Df.groupby('exercise_id').agg({
    "muscle_group":"first",
    "body_part":"first",
    "phase":"first",
    "difficulty_level":"first",
    "equipment":"first",
    "day_type":"first",
    "sets_planned":"mean",
    "reps_planned":"mean",
    "weight_planned":"mean",
    "sets_completed":"mean",
    "reps_completed":"mean",
    "weight_used":"mean",
    "rpe":"mean",
    "rest_time_sec":"mean",
    "completion_rate":"mean",
    "next_sets":"mean",
    "next_reps":"mean",
    "next_weight":"mean",
}).reset_index()

model_Df.head()

   exercise_id muscle_group body_part   phase difficulty_level    equipment day_type  sets_planned  reps_planned  weight_planned  sets_completed  reps_completed  weight_used  rpe  rest_time_sec  completion_rate  next_sets  next_reps  next_weight
0            1  hip_flexors     waist    main         Beginner  body_weight      abs           3.0          16.5             0.0             3.0            16.5          0.0  5.5           60.0            1.000        3.5       19.0          0.0
1           45   quadriceps      legs    main     Intermediate      barbell     legs           4.0           8.0            82.5             4.0             7.5         82.5  7.5          120.0            0.935        4.5        7.0         87.5
2           78   hamstrings      legs  warmup         Beginner  body_weight     legs           2.0          12.0             0.0             2.0            12.0          0.0  4.0           45.0            1.000        2.0       15.0          0.0
3           90    full_body     relax   relax         Beginner         none     legs           1.0          10.0             0.0             1.0            10.0          0.0  2.0           30.0            1.000        1.0       10.0          0.0

In [61]:
model_Df.columns

Index(['exercise_id', 'muscle_group', 'body_part', 'phase', 'difficulty_level',
       'equipment', 'day_type', 'sets_planned', 'reps_planned',
       'weight_planned', 'sets_completed', 'reps_completed', 'weight_used',
       'rpe', 'rest_time_sec', 'completion_rate', 'next_sets', 'next_reps',
       'next_weight'],
      dtype='object')

### **Sets Model**

In [62]:
sets_Df = model_Df[['exercise_id', 'muscle_group', 'body_part', 'phase', 'difficulty_level','equipment', 
                    'day_type', 'sets_planned','sets_completed','rest_time_sec', 'completion_rate', 'next_sets']]

sets_Df.head()

   exercise_id muscle_group body_part   phase difficulty_level    equipment day_type  sets_planned  sets_completed  rest_time_sec  completion_rate  next_sets
0            1  hip_flexors     waist    main         Beginner  body_weight      abs           3.0             3.0           60.0            1.000        3.5
1           45   quadriceps      legs    main     Intermediate      barbell     legs           4.0             4.0          120.0            0.935        4.5
2           78   hamstrings      legs  warmup         Beginner  body_weight     legs           2.0             2.0           45.0            1.000        2.0
3           90    full_body     relax   relax         Beginner         none     legs           1.0             1.0           30.0            1.000        1.0

In [63]:
set_x = sets_Df.drop(columns='next_sets')
set_y = sets_Df[['next_sets']]

In [64]:
# here we are using one hot coding for encode the categorical columns
set_object_cols = set_x.select_dtypes("object").columns
set_num_cols = set_x.select_dtypes(include=['int64', 'float64']).columns

In [65]:
set_preprocessor= ColumnTransformer(
    transformers=[
        ('object', OneHotEncoder(sparse_output=False, drop='first'), set_num_cols),
        ('numerical', StandardScaler(), set_num_cols)
    ]
)

sets_pipeline = Pipeline(steps=[
    ('preprocessor', set_preprocessor),
    ('regression_model', LinearRegression())
])

In [66]:
sets_pipeline.fit(set_x, set_y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('object',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  Index(['exercise_id', 'sets_planned', 'sets_completed', 'rest_time_sec',
       'completion_rate'],
      dtype='object')),
                                                 ('numerical', StandardScaler(),
                                                  Index(['exercise_id', 'sets_planned', 'sets_completed', 'rest_time_sec',
       'completion_rate'],
      dtype='object'))])),
                ('regression_model', LinearRegression())])

In [67]:
X_train, X_test, y_train, y_test = train_test_split(set_x, set_y, test_size=0.2, random_state=42)

In [68]:
# Evaluate
score = sets_pipeline.score(X_test, y_test)
print(f"Model R² score: {score:.3f}")

# Make predictions
predictions = sets_pipeline.predict(X_test)
print(f"Predictions: {predictions[:5]}")  # First 5 predictions

Model R² score: nan
Predictions: [[4.5]]

### **Reps Model**

In [69]:
reps_Df = model_Df[['exercise_id', 'muscle_group', 'body_part', 'phase', 'difficulty_level','equipment', 'day_type',
           'reps_planned','reps_completed', 'rpe', 'rest_time_sec', 'completion_rate', 'next_reps']]
reps_Df.head()

   exercise_id muscle_group body_part   phase difficulty_level    equipment day_type  reps_planned  reps_completed  rpe  rest_time_sec  completion_rate  next_reps
0            1  hip_flexors     waist    main         Beginner  body_weight      abs          16.5            16.5  5.5           60.0            1.000       19.0
1           45   quadriceps      legs    main     Intermediate      barbell     legs           8.0             7.5  7.5          120.0            0.935        7.0
2           78   hamstrings      legs  warmup         Beginner  body_weight     legs          12.0            12.0  4.0           45.0            1.000       15.0
3           90    full_body     relax   relax         Beginner         none     legs          10.0            10.0  2.0           30.0            1.000       10.0

In [70]:
reps_x = reps_Df.drop(columns='next_reps')
reps_y = reps_Df[['next_reps']]

In [71]:
# here we are using one hot coding for encode the categorical columns
reps_object_cols = reps_x.select_dtypes("object").columns
reps_num_cols = reps_x.select_dtypes(include=['int64', 'float64']).columns

In [72]:
reps_preprocessor= ColumnTransformer(
    transformers=[
        ('object', OneHotEncoder(sparse_output=False, drop='first'), reps_object_cols),
        ('numerical', StandardScaler(), reps_num_cols)
    ]
)

reps_pipeline = Pipeline(steps=[
    ('preprocessor', reps_preprocessor),
    ('regression_model', LinearRegression())
])

In [73]:
reps_pipeline.fit(reps_x, reps_y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('object',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  Index(['muscle_group', 'body_part', 'phase', 'difficulty_level', 'equipment',
       'day_type'],
      dtype='object')),
                                                 ('numerical', StandardScaler(),
                                                  Index(['exercise_id', 'reps_planned', 'reps_completed', 'rpe', 'rest_time_sec',
       'completion_rate'],
      dtype='object'))])),
                ('regression_model', LinearRegression())])

In [74]:
X_train, X_test, y_train, y_test = train_test_split(reps_x, reps_y, test_size=0.2, random_state=42)

In [75]:
# Evaluate
score = reps_pipeline.score(X_test, y_test)
print(f"Model R² score: {score:.3f}")

# Make predictions
predictions = reps_pipeline.predict(X_test)
print(f"Predictions: {predictions[:5]}")  # First 5 predictions

Model R² score: nan
Predictions: [[7.]]

### **Weight Model**

In [76]:
weight_Df = model_Df[['exercise_id', 'muscle_group', 'body_part', 'phase', 'difficulty_level','equipment', 'day_type', 
       'weight_planned','weight_used', 'rest_time_sec', 'completion_rate', 'next_weight']]
weight_Df.head()

   exercise_id muscle_group body_part   phase difficulty_level    equipment day_type  weight_planned  weight_used  rest_time_sec  completion_rate  next_weight
0            1  hip_flexors     waist    main         Beginner  body_weight      abs             0.0          0.0           60.0            1.000          0.0
1           45   quadriceps      legs    main     Intermediate      barbell     legs            82.5         82.5          120.0            0.935         87.5
2           78   hamstrings      legs  warmup         Beginner  body_weight     legs             0.0          0.0           45.0            1.000          0.0
3           90    full_body     relax   relax         Beginner         none     legs             0.0          0.0           30.0            1.000          0.0

In [77]:
weight_x = weight_Df.drop(columns='next_weight')
weight_y = weight_Df[['next_weight']]

In [78]:
# here we are using one hot coding for encode the categorical columns
weight_object_cols = weight_x.select_dtypes("object").columns
weight_num_cols = weight_x.select_dtypes(include=['int64', 'float64']).columns

In [79]:
weight_preprocessor= ColumnTransformer(
    transformers=[
        ('object', OneHotEncoder(sparse_output=False, drop='first'), weight_object_cols),
        ('numerical', StandardScaler(), weight_num_cols)
    ]
)

weight_pipeline = Pipeline(steps=[
    ('preprocessor', weight_preprocessor),
    ('regression_model', LinearRegression())
])

In [80]:
weight_pipeline.fit(weight_x, weight_y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('object',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  Index(['muscle_group', 'body_part', 'phase', 'difficulty_level', 'equipment',
       'day_type'],
      dtype='object')),
                                                 ('numerical', StandardScaler(),
                                                  Index(['exercise_id', 'weight_planned', 'weight_used', 'rest_time_sec',
       'completion_rate'],
      dtype='object'))])),
                ('regression_model', LinearRegression())])

In [81]:
X_train, X_test, y_train, y_test = train_test_split(weight_x, weight_y, test_size=0.2, random_state=42)

In [82]:
# Evaluate
score = weight_pipeline.score(X_test, y_test)
print(f"Model R² score: {score:.3f}")

# Make predictions
predictions = weight_pipeline.predict(X_test)
print(f"Predictions: {predictions[:5]}")  # First 5 predictions

Model R² score: nan
Predictions: [[87.5]]